// Generated by scripts/generate-article-data.mjs. Edit the authoritative article sources.
export const articleCatalog = [
  {
    "slug": "meraki-october-2026-security-update",
    "title": "Cisco Meraki’s October security update: what to ask your IT provider to verify",
    "lane": "Professional services",
    "readMin": 6
  },
  {
    "slug": "accounting-firms-core-vs-command",
    "title": "Choosing between a standardized stack and full program ownership: Helm Core vs Helm Command for accounting firms",
    "lane": "Accounting firms",
    "readMin": 8
  },
  {
    "slug": "ai-access-business-documents",
    "title": "What to check before giving AI access to business documents",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "ai-phishing-red-flags",
    "title": "AI Phishing: Verification Beyond Typos",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "backup-testing-insurers",
    "title": "Backup Testing: Evidence to Prepare for Cyber Insurance Questions",
    "lane": "Professional Services",
    "readMin": 8
  },
  {
    "slug": "check-website-security",
    "title": "How to check website security: a simple step-by-step checklist for New Jersey small businesses",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "choose-first-ai-workflow",
    "title": "How to choose your first AI workflow",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "cmmc-deadline-checklist",
    "title": "CMMC After the Phase 2 Suspension: A 12-Step Checklist for Manufacturers",
    "lane": "Manufacturing & Defense",
    "readMin": 8
  },
  {
    "slug": "cmmc-level-1-vs-level-2",
    "title": "CMMC Level 1 vs Level 2: Which One Does Your Shop Actually Need?",
    "lane": "Manufacturing & Defense",
    "readMin": 8
  },
  {
    "slug": "cui-handling-shop-floor",
    "title": "Explaining CUI to Your Shop Floor: The Rules That Actually Matter",
    "lane": "Manufacturing & Defense",
    "readMin": 8
  },
  {
    "slug": "cyber-insurance-application-walkthrough",
    "title": "A Cyber Insurance Application Walkthrough: From Questions to Supported Answers",
    "lane": "Professional Services",
    "readMin": 8
  },
  {
    "slug": "cyber-insurance-claim-denied",
    "title": "Cyber Insurance Claim Disputes: Coverage, Evidence and the Questions to Resolve",
    "lane": "Professional Services",
    "readMin": 8
  },
  {
    "slug": "cyber-insurance-questionnaire",
    "title": "How to Answer a Cyber Insurance Questionnaire with Evidence",
    "lane": "Professional Services",
    "readMin": 8
  },
  {
    "slug": "cybersecurity-point-solutions-vs-managed-security",
    "title": "Cybersecurity Point Solutions vs Managed Security for NJ SMBs",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "cybersecurity-risk-assessment-tools",
    "title": "How to evaluate a cybersecurity risk assessment tool for small businesses",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "cybersecurity-roadmap-milestones",
    "title": "Key milestones to include in a cybersecurity roadmap for New Jersey professional-services firms",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "deepfake-ceo-fraud",
    "title": "Deepfake Executive Fraud: Real Cases and Verification Steps",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "digital-risk-protection-services",
    "title": "How to evaluate and implement digital risk protection services on a budget for small businesses",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "email-security-gateway-managed-service",
    "title": "Email security gateway versus managed gateway service: choosing the right model for your SMB",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "email-security-services-evaluation",
    "title": "How to evaluate email security services for small businesses: checklist and vendor questions",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "employee-offboarding-checklist",
    "title": "Employee Offboarding Checklist: Accounts, Devices and Business Continuity",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "google-workspace-retention-vs-backup",
    "title": "Google Workspace Native Retention vs Managed Backup Services: Choosing the Right Fit for Your Business",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "google-workspace-security-managed-vs-diy",
    "title": "Managed Google Workspace Security vs DIY: Which Is Right for Your SMB",
    "lane": "Professional services",
    "readMin": 9
  },
  {
    "slug": "hipaa-email-rules-small-practices",
    "title": "HIPAA Email Rules for Small Practices: What Addressable Means in Operation",
    "lane": "Professional Services",
    "readMin": 8
  },
  {
    "slug": "hipaa-risk-analysis-medical-practices",
    "title": "HIPAA Security Risk Analysis for Small Medical Practices",
    "lane": "Medical Practices",
    "readMin": 8
  },
  {
    "slug": "iam-security-core-vs-command",
    "title": "IAM Cyber Security for SMBs: How Helm Core Compares to Helm Command",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "incident-response-plan-small-business",
    "title": "Incident Response Plan for Small and Medium Businesses: The First Decisions",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "intentional-insider-threats",
    "title": "What Business Owners Need to Know About Intentional Insider Threats",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "invoice-fraud-red-flags",
    "title": "Invoice Fraud Red Flags: What to Check Before You Pay a Vendor",
    "lane": "All industries",
    "readMin": 9
  },
  {
    "slug": "job-site-devices-public-wifi",
    "title": "Job Site Devices and Public Wi-Fi: What Actually Puts a Contractor at Risk",
    "lane": "Contractors & Trades",
    "readMin": 8
  },
  {
    "slug": "law-firm-device-security-checklist",
    "title": "Law Firm Device Security Checklist: Laptops, Remote Work, and Lost Devices",
    "lane": "Law Firms",
    "readMin": 8
  },
  {
    "slug": "law-firm-managed-vs-in-house-security",
    "title": "In-House vs Managed Cybersecurity for Law Firms: Pros, Cons, and Budget-Friendly Choices",
    "lane": "Law firms",
    "readMin": 8
  },
  {
    "slug": "m365-security-baseline",
    "title": "Microsoft 365 Security Baseline: Access, Mail and Recovery",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "managed-awareness-training-vs-diy",
    "title": "Managed cyber security awareness training programs versus DIY: choosing the right path for your SMB",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "managed-endpoint-protection-rollout",
    "title": "How to Implement Endpoint Security Protection with a Managed Service: Assessment, Rollout, and Ongoing Evidence",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "managed-identity-threat-response",
    "title": "Key capabilities to look for in a managed identity threat detection and response provider",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "measure-ai-time-savings",
    "title": "Is AI saving your team time? Count the checking and corrections",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "mfa-methods-compared",
    "title": "MFA Methods Compared: SMS, TOTP, Push and Passkeys",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "microsoft-365-retention-vs-backup",
    "title": "Microsoft 365 Native Retention vs Third-Party Backup: Which Is Right for Your Small Business",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "outlook-email-encryption-options",
    "title": "S/MIME vs Office 365 Message Encryption vs TLS: Choosing the Right Outlook Encryption for Your Company",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "password-managers-small-teams",
    "title": "Password Managers for Small Teams: What a Business Vault Adds",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "security-questionnaire-response-services",
    "title": "Security questionnaire response services versus DIY: what SMBs should consider",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "shadow-ai-at-work",
    "title": "Shadow AI: What Employees Paste into Chatbots When Nobody Is Looking",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "siem-software-managed-detection",
    "title": "How small businesses in New Jersey should evaluate SIEM security software and managed detection services",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "sprs-score-explained",
    "title": "SPRS Score Explained: What the Number Means and How to Support It",
    "lane": "Manufacturing & Defense",
    "readMin": 8
  },
  {
    "slug": "ssp-poam-explained",
    "title": "SSP and POA&M Explained: The Evidence Behind CMMC Readiness",
    "lane": "Manufacturing & Defense",
    "readMin": 8
  },
  {
    "slug": "vendor-email-compromise-contractors",
    "title": "Vendor Email Compromise: When Your Supplier's Invoice Is Actually a Scam",
    "lane": "Contractors & Trades",
    "readMin": 8
  },
  {
    "slug": "virtual-ciso-service-evaluation",
    "title": "How to Choose a Virtual CISO Service That Delivers Roadmaps, Evidence, and Quarterly Accountability",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "vulnerability-management-new-jersey",
    "title": "How to build a vulnerability management program for small businesses in New Jersey",
    "lane": "Professional services",
    "readMin": 9
  },
  {
    "slug": "what-a-soc-actually-does",
    "title": "What a SOC Actually Does: Monitoring, Investigation and Response",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "what-is-dmarc",
    "title": "What Is DMARC? A Plain-English Guide for Business Owners",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "windows-defender-vs-managed-security",
    "title": "Windows Defender vs Managed Endpoint Security: Which Is Right for Your New Jersey Business",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "wire-fraud-prevention-law-firms",
    "title": "Wire Fraud Prevention for Law Firms: The Callback Protocol",
    "lane": "Law Firms",
    "readMin": 9
  },
  {
    "slug": "wisp-checklist-accounting-firms",
    "title": "WISP Checklist for Tax and Accounting Firms",
    "lane": "Accounting Firms",
    "readMin": 8
  },
  {
    "slug": "zero-day-vs-known-vulnerabilities",
    "title": "Zero-Day vs Known Vulnerabilities: How Patch Management, Threat Intelligence, and Managed Services Reduce Your Risk",
    "lane": "Professional services",
    "readMin": 8
  },
  {
    "slug": "pen-test-vs-vulnerability-scan",
    "title": "Penetration Testing vs Vulnerability Scanning: What Your Business Should Buy",
    "lane": "Small business",
    "readMin": 9
  },
  {
    "slug": "dns-filtering-small-business",
    "title": "DNS Filtering for Small Business: Coverage, Limits and a Rollout Checklist",
    "lane": "Small business",
    "readMin": 9
  },
  {
    "slug": "network-hardening-small-business",
    "title": "Network Hardening for Small Business: A Checklist Your IT Provider Can Use",
    "lane": "Small business",
    "readMin": 9
  },
  {
    "slug": "disaster-recovery-small-business",
    "title": "Disaster Recovery for Small Business: A Plan You Can Test",
    "lane": "Small business",
    "readMin": 10
  },
  {
    "slug": "cyber-insurance-cybersecurity-vendors",
    "title": "How to evaluate and select a cybersecurity partner that proves your controls to insurers",
    "lane": "All industries",
    "readMin": 10
  },
  {
    "slug": "managed-service-provider-security-models",
    "title": "Comparing Managed Service Provider Models: Standard Security Stack versus Full Program Ownership",
    "lane": "All industries",
    "readMin": 8
  },
  {
    "slug": "managed-service-providers-new-jersey",
    "title": "Seven signs your company needs a managed service provider, and what to do next",
    "lane": "All industries",
    "readMin": 8
  }
];
