/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme.ts
 * Command: astryx theme build src/theme.ts --out src/theme.css
 * Generated: 2026-08-04T19:38:44.783Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const helmTheme: DefinedTheme;
